[package]
name = "nsticky"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
